### ISSUE TITLE
Add CLI helper

### ISSUE THREAD

**Issue by hrajwade96** [hrajwade96/flutter_plugins_list#1]
#### Description
Add support for a command-line interface (CLI) helper. This feature will provide users with assistance on how to use the tool, including available commands, options, and usage examples.

#### Tasks
- [ ] Implement a CLI helper that displays available commands and their descriptions.
- [ ] Add a `--help` or `-h` option to display the helper information.
- [ ] Ensure the CLI helper includes usage examples.

#### Example
When a user runs the following command:
```sh
flutter_plugins_list --help
```
Output could be :

flutter_plugins_list: A tool to list and manage Flutter plugin dependencies.

Usage:
  flutter_plugins_list [options]

Options:
  --help, -h       Display this help message and exit.
  --version, -v    Display the version information and exit.
  --output, -o     Specify the output format (csv, json).
  
Examples:
  flutter_plugins_list --help
  flutter_plugins_list --output csv
